[package]
name = "rustbot"
version = "0.1.0"
authors = ["Peter Foley <pefoley2@pefoley.com>"]
edition = "2024"

[dependencies]
irc = "*"
time = "*"

[dependencies.tokio]
 version = "*"
 features = ["macros", "rt-multi-thread"]
