[package]
name = "rustbot"
version = "0.1.0"
authors = ["Peter Foley <pefoley2@pefoley.com>"]
edition = "2021"

[dependencies]
irc = "*"

[dependencies.tokio]
 version = "*"
 features = ["macros", "rt-multi-thread"]
